### ISSUE TITLE
Support for cached geohash and elevation values

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#150]
For cesium to properly support elevation values, we need to have a geohash and an elevation value.  This will require changes in a number of places.   Initial outline is as follows:

> (1) On ingest into the things db, assign a geohash to every new thing and store in the thing row (we will use this later)
(2) After things ingest, have the elevate JS tool do a query for geohashes that aren't present in the things table, and insert them if they aren't present
(3) At solr index time, consult the points table which will have been updated in step (2)
(4) During sitemap ingestion at iSamples Central time, we'll include both the geohash and the elevation value for each thing.  The sitemap ingestion tool will be responsible for updating the points table on iSamples Central

> So the tasks would be
(1) new column in Things table for geohash ISB,ISC
(2) update Things ingest tool to populate the geohash as things are saved ISB
(3) update elevate tool to speak postgresql and also do intelligent queries for missing geohashes in the points table  (e.g. select distinct geohash from Thing where geohash not in <list of geohashes with existing elevations>) ISB
(4) update index script to use the Things geohash value and elevation on insert ISB,ISC
(5) update sitemap api to include the geohash and elevation as part of the response ISB
(6) update sitemap ingest tool to parse the geohash and elevation from the response, and insert into appropriate tables ISC

**Comment by datadavev** [comment]
On further research, we can gain some benefit by switching the geohash algorithm for H3[^1]. The hexagonal geometry provides a number of benefits such as good tools in multiple languages for computing basic geometry operations such as returning hashes within a distance of a hash, computing hashes within a region, etc.

No changes are required other than using the h3 hash algorithm instead of the geohash algorithm to compute a hash value given coordinates.

Hashes should be calculated at the highest resolution of 15 which corresponds with a sub-meter resolution globally [^2].

[^1]: https://h3geo.org/
[^2]: https://h3geo.org/docs/core-library/restable

**Comment by dannymandel** [comment]
This has been implemented.
